### ISSUE TITLE
lack of file "generate_offline_data"

### ISSUE THREAD

**Issue by luckywlj** [LiangZhang1996/DataLight#5]
According to your paper and the README, your code repository  is lack of the file "generate_offline_data" so as to fail to run the offline rl code.  Could you please provide this file?
When I run the file "run_offline.py", error occurs as follows:

NotADirectoryError: [Errno 20] Not a directory: './memory/cycle_mix.pkl'

**Comment by LiangZhang1996** [comment]
I am updating my article and the source code.
There is a large difference, and I will refresh this project in one month.

**Comment by luckywlj** [comment]
Thank you for your works! Respect!

**Comment by luckywlj** [comment]
Just now, I found that you provide the link of memory and there are three data files can be downloaded. How to place the data file to the ./memory? Because the memory is a  file but not a directory.

**Comment by LiangZhang1996** [comment]
1. make a directory "./memory/"
2. place the downloaded files at this directory as: "./memeory/cycle_mix.pkl"

**Comment by luckywlj** [comment]
I have finished the two steps and run "run_offline.py", there is errors as follows:
![Uploading 2023-10-16 22-41-10 的屏幕截图.png…]()
[](url)

**Comment by luckywlj** [comment]
I have finished the two steps and run "run_offline.py", there is errors as follows:

![2023-10-16 22-41-10 的屏幕截图](https://github.com/LiangZhang1996/DataLight/assets/53700751/de34f1aa-ccc8-456f-87b6-0b6582c7a078)

My tenserflow version is 2.11 and python version is 3.7.4.

**Comment by LiangZhang1996** [comment]
It is the problem that you cannot load the pickle file.
It may be the incorrect version of pickle.
Maybe you could use a lower version of pickle or refer to stackoverflow

**Comment by luckywlj** [comment]
> It is the problem that you cannot load the pickle file. It may be the incorrect version of pickle. Maybe you could use a lower version of pickle or refer to stackoverflow

Thanks a lot, I try it again.

**Comment by luckywlj** [comment]
After running  "run_offline.py", I respectively run "run_cycle.py" and "run_test.py" and obtain the following errors:

python run_cycle.py

Process Process-2:
Traceback (most recent call last):
  File "/home/luckywlj/anaconda3/envs/cityflow/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/luckywlj/anaconda3/envs/cityflow/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_cycle.py", line 164, in testor_wrapper
    old_round)
  File "run_cycle.py", line 186, in __init__
    intersection_id=str(0)
  File "/home/luckywlj/traffic_signal_control/DataLight-main/models/network_agent.py", line 46, in __init__
    if os.listdir(self.dic_path["PATH_TO_MODEL"]):
FileNotFoundError: [Errno 2] No such file or directory: 'model/benchmark_0214_2/anon_3_4_jinan_real3.json_02_14_18_54_26'
traffic finish join 0
traffic to join 1
traffic finish join 1


python run_test.py
..........
__________________
Process Process-1:
Traceback (most recent call last):
  File "/home/luckywlj/anaconda3/envs/cityflow/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/luckywlj/anaconda3/envs/cityflow/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run_test.py", line 159, in testor_wrapper
    old_round)
  File "run_test.py", line 181, in __init__
    intersection_id=str(0)
  File "/home/luckywlj/traffic_signal_control/DataLight-main/models/network_agent.py", line 46, in __init__
    if os.listdir(self.dic_path["PATH_TO_MODEL"]):
FileNotFoundError: [Errno 2] No such file or directory: 'model/benchmark_0216_13/anon_3_4_jinan_real3.json_02_16_22_14_17'
traffic finish join 0
traffic to join 1
traffic finish join 1

both errors imply the lack of model/benchmark_0216_13/anon_3_4_jinan_real3.json_02_16_22_14_17. I check the model folder and there is only a sub folder "benchmark_1001". I check the utils/config.py and the code is ' "PATH_TO_MODEL": "model/default" '. I think the two code files can not find the data of jinan 3x4, but the data is in their running configurations so as to  throw errors. Could you please tell me how to do?

**Comment by luckywlj** [comment]
> It would help if you used the correct folder path.

You mean that the folder "records" is the correct folder? But there is no jinan3x3 in this folder. So I want to know how to solve the  problem of lack of jinan3x3 data.
